default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: wwc_database-dev

test:
  <<: *default
  database: wwc_database-test

production:
  <<: *default
  database: wwc_database-prod
